stages:
  - lint
  - test
  - build

variables:
  PYTHON_VERSION: "3.9"

lint:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - pip install flake8
    - flake8 formfiller.py src/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest test/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  image: python:${PYTHON_VERSION}
  script:
    - python -m pip install --upgrade pip
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/
  only:
    - tags